import type { ContentPiece, Product, ProductAnalysis } from './types';

const TODAY = '2026-09-09';

export const INITIAL_PRODUCTS: Product[] = [{
  id: 'hilee-2em1',
  name: 'Garrafa Hilee 2 em 1',
  emoji: '\ud83e\uddf4',
  description: 'Garrafa de \u00e1gua com tampas intercambi\u00e1veis, a\u00e7o inoxid\u00e1vel, antivazamento',
  shopUrl: 'https://shop.tiktok.com/br/pdp/garrafa-hilee-2-em-1-tampas-intercambiaveis-aco-inoxidavel-antivazamento/1735072257743160874',
  createdAt: '2026-09-09',
}];

export const INITIAL_HOOKS: ContentPiece[] = [
  // ── ANGLE 1: nao-vaza (8 hooks) ──
  {
    id: 'h1',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'nao-vaza',
    text: 'Bonita ela \u00e9, n\u00e9? Agora eu quero saber mesmo se n\u00e3o vai vazar \u00e1gua dentro da minha bolsa, vamos ver',
    visualHook: 'Close na garrafinha na m\u00e3o. Vira de cabe\u00e7a pra baixo. Segura. C\u00e2mera fixa.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h2',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'nao-vaza',
    text: 'Se tem uma coisa que acaba com meu dia \u00e9 voc\u00ea jogar a garrafa dentro da bolsa e ela simplesmente vazar \u00e1gua por tudo. Esse meu problema ACABOU depois que eu comprei essa garrafinha aqui, deixa eu te mostrar.',
    visualHook: 'Abre a bolsa, garrafinha dentro, virada. Mostra que t\u00e1 tudo seco.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h3',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'nao-vaza',
    text: 'Eu confesso pra voc\u00eas que duvidei que essa tampinha aqui de canudo n\u00e3o ia vazar \u00e1gua, t\u00e1? Mas olha isso, simplesmente n\u00e3o cai uma gota',
    visualHook: 'Close na tampa de canudo. Vira a garrafinha com a tampa. Nada cai.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h4',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'nao-vaza',
    text: 'Miga, eu vou virar essa garrafinha de cabe\u00e7a pra baixo dentro da minha bolsa agora. Com tudo dentro. Celular, carteira, tudo. Olha isso...',
    visualHook: 'Garrafinha dentro da bolsa. Vira a bolsa de lado. Abre. Mostra tudo seco.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h5',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'nao-vaza',
    text: 'Migas, o povo jurou que n\u00e3o vaza. JUROU. Ent\u00e3o eu vou balan\u00e7ar de verdadeeee aqui, olha, com for\u00e7a t\u00e1? E vamos ver...',
    visualHook: 'Segura a garrafinha e balan\u00e7a com for\u00e7a na frente da c\u00e2mera.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h6',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'nao-vaza',
    text: 'Migas, eu j\u00e1 estraguei caderno, fone de ouvido e necessaire por causa de garrafa vazando na bolsa. A\u00ed eu comprei essa aqui e no come\u00e7o fiquei desconfiada, t\u00e1? Olha o que eu vou fazer agora...',
    visualHook: 'Close na garrafinha fechada. Vira. Balan\u00e7a. C\u00e2mera est\u00e1tica, sem corte.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h7',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'nao-vaza',
    text: 'Migas, eu n\u00e3o tava entendendo por que o povo fala TANTO dessa garrafinha. A\u00ed eu fiz isso aqui, olha, t\u00f4 virando e balan\u00e7ando com tudo, e genteee... agora eu entendi.',
    visualHook: 'Garrafinha parada na mesa, pega e come\u00e7a a balan\u00e7ar.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h8',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'nao-vaza',
    text: 'Bonita. N\u00e3o vaza. Cabe na bolsa. Migas, eu achava que essa garrafa n\u00e3o existia. A\u00ed olha o que apareceu na minha for you...',
    visualHook: 'Tr\u00eas takes r\u00e1pidos: garrafinha na m\u00e3o / dentro da bolsa / virada. Corte seco.',
    status: 'ready',
    createdAt: TODAY,
  },

  // ── ANGLE 2: estetica (8 hooks) ──
  {
    id: 'h9',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'estetica',
    text: 'Eu precisava de uma garrafinha? N\u00e3o precisava\u2026 Mas fala s\u00e9rioooo como que eu n\u00e3o ia comprar isso aqui se \u00e9 a MINHA CARA',
    visualHook: 'Garrafinha girando devagar na m\u00e3o. Luz natural. Close na estampa.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h10',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'estetica',
    text: 'Miga, a gente trabalha pra qu\u00ea se n\u00e3o pode comprar uma coisinha de garouuutcha de vez em quando? Ah olha essa garrafinha aqui, fala s\u00e9rio',
    visualHook: 'Coloca a garrafinha na mesa do escrit\u00f3rio. Arruma do lado das suas coisas.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h11',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'estetica',
    text: 'Eu tava rolando a for you e vi essa garrafinha, pensei \u2018n\u00e3o preciso\u2019. A\u00ed vi as cores e estampas perfeitas, a\u00ed vi que troca de tampa e vira um copo\u2026 comprei n\u00e9 migas.',
    visualHook: 'Tela do celular na p\u00e1gina do TikTok Shop. Corte pra garrafinha real na m\u00e3o.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h12',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'estetica',
    text: 'Miga eu comprei essa garrafinha S\u00d3 pela estampa, t\u00e1? Nem li a descri\u00e7\u00e3o. A\u00ed ela chegou e veio com DUAS tampas. Eu pensei \u2018u\u00e9?\u2019. Gente, olha o que essa garrafinha faz...',
    visualHook: 'Tira da caixa. Close na estampa.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h13',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'estetica',
    text: 'Miga eu s\u00f3 ia comprar uma garrafa de \u00e1gua simples, juro. A\u00ed eu vi essa estampaaaaa e gente, n\u00e3o teve a menor condi\u00e7\u00e3o. OLHA ISSO.',
    visualHook: 'Close passando o dedo na estampa. Mostrando o detalhe. Devagar.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h14',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'estetica',
    text: 'Se eu vou passar o dia inteiro com uma garrafinha do meu lado, pelo menos vai ter que ser uma lindaaaa assim n\u00e9?',
    visualHook: 'Garrafinha na mesa do escrit\u00f3rio do lado do notebook. Tudo combinando.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h15',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'estetica',
    text: 'Ah gente, voc\u00eas v\u00e3o me desculpar mas eu romantizo a vida SIM, t\u00e1? At\u00e9 minha garrafa de \u00e1gua tem que ser linda. Olha essa aqui e me diz se eu t\u00f4 errada, fala s\u00e9rio.',
    visualHook: 'Garrafinha com caf\u00e9/\u00e1gua na mesa com luz de janela. Aesthetic.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h16',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'estetica',
    text: 'Toooooda vez que algu\u00e9m v\u00ea essa garrafinha aqui em cima da mesa do escrit\u00f3rio me perguntam de onde \u00e9',
    visualHook: 'Garrafinha em cima da mesa. M\u00e3o entra no quadro e pega. Natural.',
    status: 'ready',
    createdAt: TODAY,
  },

  // ── ANGLE 3: 2em1 (4 hooks) ──
  {
    id: 'h17',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: '2em1',
    text: 'Eu achei que tinha comprado uma garrafinha de \u00e1gua e simplesmente ganhei um copo t\u00e9rmico.',
    visualHook: 'Garrafinha com uma tampa. Corte. Mesma garrafinha com a outra tampa.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h18',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: '2em1',
    text: 'Miga olha s\u00f3 essa garrafinha, com essa tampa eu jogo ela dentro da minha bolsa e levo para qualquer lugar, porque n\u00e3o vaza, a\u00ed quando quero usar aqui no escrit\u00f3rio troco a tampa e fica um copinho com canudo para eu deixar aqui na mesa.',
    visualHook: 'Close nas m\u00e3os trocando a tampa. O gesto. O clique.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h19',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: '2em1',
    text: 'COMO que eu vivi tanto tempo sem isso, migas?? Olha, eu troco essa tampa aqui e a garrafinha vira um copinho com canudo. UMA garrafinha, dois usos. Genteee.',
    visualHook: 'As duas tampas na mesa. Pega uma, encaixa. Pega a outra, encaixa.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h20',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: '2em1',
    text: 'Miga, eu vou trocar a tampa dessa garrafinha aqui agora e voc\u00ea vai entender por que eu n\u00e3o paro de falar dela. Olha isso.',
    visualHook: 'Garrafinha parada. M\u00e3o tira a tampa. Coloca a outra. C\u00e2mera fixa.',
    status: 'ready',
    createdAt: TODAY,
  },

  // ── ANGLE 4: tamanho (6 hooks) ──
  {
    id: 'h21',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'tamanho',
    text: 'Eu aposto que voc\u00ea tamb\u00e9m comprou o tal do copo de \u00e1gua hypado, n\u00e9? Eu comprei, a\u00ed todo dia passava raiva porque esse trem \u00e9 enoooorme e vaza \u00e1gua por tudo. At\u00e9 que decidi comprar essa garrafinha aqui.',
    visualHook: 'Coloca a garrafinha dentro da bolsa. Cabe.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h22',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'tamanho',
    text: 'Migas, eu vi uma menina falando que tinha comprado essa garrafinha pra deixar aqui no porta copos do carro, a\u00ed eu decidi testar, olha isso aqui, cabe peeeerfeito.',
    visualHook: 'Dentro do carro. Coloca no porta-copos. Encaixa.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h23',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'tamanho',
    text: 'Voc\u00ea tamb\u00e9m compra aqueles copos enormes e depois deixa todos em casa porque n\u00e3o cabe em lugar nenhum? Foi exatamente por isso que eu quis uma garrafinha desse tamanho.',
    visualHook: 'Garrafinha na lateral da mochila. Encaixou. Close.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h24',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'tamanho',
    text: 'Eu sei que cop\u00e3o grande de \u00e1gua igual esse aqui \u00e9 \u00f3timo porque a gente n\u00e3o tem que ficar enchendo toda hora, mas pra levar pra rua dentro da bolsa, uma garrafinha desse tamanho \u00e9 muitoooo melhor',
    visualHook: 'Segura a garrafinha do lado de um cop\u00e3o grande. Compara.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h25',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'tamanho',
    text: 'Miga, nenhuma garrafinha que eu comprava cabia no bolsinho lateral da mochila da academia. NENHUMA. At\u00e9 eu testar essa aqui, olha issooooo.',
    visualHook: 'Tenta colocar outra garrafa no bolso da mochila. N\u00e3o cabe. Coloca a Hilee. Cabe.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h26',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'tamanho',
    text: 'Sabe o que eu mais amo nessa garrafinha? Que ela cabe no porta-copos do carro certinhoooo. Nenhuma outra que eu tinha cabia.',
    visualHook: 'Porta-copos do carro. M\u00e3o coloca a garrafinha. Encaixa perfeito.',
    status: 'ready',
    createdAt: TODAY,
  },

  // ── ANGLE 5: temperatura (3 hooks) ──
  {
    id: 'h27',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'temperatura',
    text: 'Migas, vi o povo falando que a garrafinha segura a temperatura por hooooras n\u00e9? Da\u00ed eu quis testar, coloquei gelo agora 08h da manh\u00e3 e vamos ver quanto tempo dura.',
    visualHook: 'Coloca gelo na garrafinha. Close no gelo caindo dentro. Mostra o hor\u00e1rio no celular.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h28',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'temperatura',
    text: 'Migas eu coloquei gelo nessa garrafinha a hora que sa\u00ed de casa 8h da manh\u00e3, agora s\u00e3o 18h e olha isso, ainda tem gelo aqui.',
    visualHook: 'Mostra o hor\u00e1rio no celular (18h). Abre a garrafinha. Balan\u00e7a. Som de gelo.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h29',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'temperatura',
    text: 'Como eu ainda n\u00e3o tinha pensado em usar essa garrafinha da hilee para colocar caf\u00e9? Ficou o tamanho peeerfeito',
    visualHook: 'Coloca caf\u00e9 na garrafinha. Fecha a tampa. Close.',
    status: 'ready',
    createdAt: TODAY,
  },

  // ── ANGLE 6: uso-inesperado (3 hooks) ──
  {
    id: 'h30',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'uso-inesperado',
    text: 'Sinceramente eu n\u00e3o comprei essa garrafinha para isso, mas olha aqui, n\u00e3o ficou o tamanho perfeito para colocar um cafezinho e trazer para o escrit\u00f3rio?',
    visualHook: 'Garrafinha na mesa do trabalho com caf\u00e9 dentro. Bebe pelo canudo.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h31',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'uso-inesperado',
    text: 'Migas, quer saber por que eu t\u00f4 tomando o DOBRO de \u00e1gua? Por causa dessa tampinha aqui com canudo. Coloco do lado da mesa e bebo sem nem perceber, \u00e9 autom\u00e1ticoooo.',
    visualHook: 'Garrafinha com canudo do lado do notebook. M\u00e3o pega, bebe, coloca de volta. Autom\u00e1tico.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h32',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'uso-inesperado',
    text: 'Eu vou te mostrar uma coisa e voc\u00ea vai querer comprar.',
    visualHook: 'Segura a garrafinha tampada. Gira na m\u00e3o mostrando.',
    status: 'ready',
    createdAt: TODAY,
  },

  // ── ANGLE 7: criancas (10 hooks) ──
  {
    id: 'h33',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'criancas',
    text: 'POV: voc\u00ea \u00e9 m\u00e3e de menina e acabou de encontrar a garrafinha perfeita.',
    visualHook: 'Garrafinha 350ml na mochilinha infantil. Close. Cabe na lateral.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h34',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'criancas',
    text: 'Olha essa dica para as mam\u00e3es. Eu tinha esse garrafinha aqui da hilee no tamanho 500 ml, s\u00f3 que ela \u00e9 muito grande para crian\u00e7as, a\u00ed peguei para a luiza essa aqui de 350ml.',
    visualHook: 'As duas garrafas na mesa: 500ml e 350ml lado a lado. M\u00e3o aponta pra menor.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h35',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'criancas',
    text: 'Eu gostei tanto da minha Hilee de 500 ml que, quando vi que tinha essa vers\u00e3o menor pensei NA HORA de pegar uma para minha filha.',
    visualHook: 'Segura a de 500ml. Coloca do lado da de 350ml. Compara.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h36',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'criancas',
    text: 'Eu queria uma garrafinha que minha filha conseguisse abrir sozinha, que n\u00e3o vazasse \u00e1gua e que fosse bonita. Acheeei.',
    visualHook: 'M\u00e3ozinha abrindo a tampa da garrafinha sozinha.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h37',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'criancas',
    text: 'Miga, se sua filha volta da escola com a mochila todaaaa molhada por causa da garrafa, olha essa aqui que eu achei.',
    visualHook: 'Garrafinha 350ml na lateral da mochilinha. Fecha o el\u00e1stico. Cabe certinho.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h38',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'criancas',
    text: 'Migas eu comprei essa garrafinha da hilee de 350ml para minha filha, olha como o tamanho \u00e9 perfeito! Eu consigo encaixar aqui na lateral da bolsa dela e a \u00e1gua fica geladinha durante todo o passeio.',
    visualHook: 'Garrafinha na bolsinha. Close.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h39',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'criancas',
    text: 'Se voc\u00ea tem crian\u00e7a pequena, precisaaaa dessa garrafinha aqui, olha isso, o tamanho \u00e9 perfeito.',
    visualHook: 'Garrafinha 350ml na m\u00e3o mostrando o tamanho compacto.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h40',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'criancas',
    text: 'Migas eu amei TANTO essa garrafinha da hilee que fui l\u00e1 e comprei uma para o Pedro tamb\u00e9m, olha s\u00f3 essa cor',
    visualHook: 'Duas garrafas de cores diferentes na mesa.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h41',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'criancas',
    text: 'Essa aqui \u00e9 minha garrafinha hilee de 500ml e essa pequenininha \u00e9 a da luiza, minha filha. Olha como esse tamanho fica muito melhor para crian\u00e7a segurar',
    visualHook: '500ml e 350ml lado a lado. Close mostrando a diferen\u00e7a.',
    status: 'ready',
    createdAt: TODAY,
  },
  {
    id: 'h42',
    productId: 'hilee-2em1',
    type: 'hook',
    angle: 'criancas',
    text: 'Migas, sabe quantas garrafinhas eu testei at\u00e9 achar uma que minha filha conseguisse abrir SOZINHA e que n\u00e3o vazasse na mochila? Muuuitas. Essa aqui foi a primeira que passou.',
    visualHook: 'Garrafinha 350ml sendo aberta com uma m\u00e3o s\u00f3.',
    status: 'ready',
    createdAt: TODAY,
  },
];

export const INITIAL_ANALYSES: ProductAnalysis[] = [{
  productId: 'hilee-2em1',
  price: 'R$80,80',
  originalPrice: 'R$85,00',
  discount: '5%',
  shipping: 'Gratis',
  rating: '4.9',
  reviewCount: '3.035',
  soldCount: '16.700',
  seller: 'Hilee Brasil',
  sizes: ['350ml', '500ml'],
  colors: ['Rosa Suave', 'Roxo Lavanda', 'Cinza Classico', 'Amarelo Pastel', 'Branco & Preto', 'Branco Puro', 'Azul Laco', 'Vermelho Edicao Limitada', 'Magic Card', 'Love', 'Handy Charm', 'Flor Branca', 'Floresta dos Gatos', 'Tulipa', 'Festa na Praia', 'Laco dos Sonhos', 'Anjo Rosa', 'Academia dos Filhotes', 'Gatinho Azul'],
  material: 'Aco inoxidavel com isolamento a vacuo',
  features: [
    {
      id: 'f1', category: 'structural', feature: 'Corpo em aco inoxidavel',
      why: 'Duravel, nao amassa, nao descasca. Nao e plastico barato.',
      whatItDoes: 'Resiste a quedas, batidas e uso diario sem amassar ou quebrar.',
      dimensioned: 'Uma garrafa que aguenta a vida corrida sem perder a beleza.',
      emotionPositive: 'Confianca, durabilidade, sensacao de qualidade',
      emotionNegative: 'Medo de garrafa barata que quebra ou descasca',
      ranking: 4
    },
    {
      id: 'f2', category: 'structural', feature: 'Isolamento termico a vacuo (dupla parede)',
      why: 'Agua gelada o dia inteiro, cafe quente por horas. Sem bebida morna.',
      whatItDoes: 'Mantem a bebida gelada por horas no calor e quente no frio, sem suar por fora.',
      dimensioned: 'O cafe da manha ainda quente quando chega no trabalho. A agua com gelo ainda gelada as 18h.',
      emotionPositive: 'Conforto, autocuidado, sensacao de luxo no dia a dia',
      emotionNegative: 'Frustracao com bebida morna, gastar dinheiro comprando agua na rua',
      ranking: 4
    },
    {
      id: 'f3', category: 'structural', feature: 'Tamanho 350ml (compacto)',
      why: 'Cabe na bolsa pequena, na Longchamp, na lancheira do filho.',
      whatItDoes: 'Cabe dentro de bolsas pequenas e medias sem ocupar espaco ou pesar.',
      dimensioned: 'A garrafinha que vai junto pra todo lugar sem atrapalhar nada.',
      emotionPositive: 'Leveza, praticidade, liberdade',
      emotionNegative: 'Irritacao com garrafa grande que nao cabe em lugar nenhum',
      ranking: 4
    },
    {
      id: 'f4', category: 'structural', feature: 'Tamanho 500ml (intermediario)',
      why: 'Capacidade pro dia inteiro sem ser aquele garrafao enorme.',
      whatItDoes: 'Garante hidratacao suficiente pro dia sem precisar reabastecer toda hora.',
      dimensioned: 'Hidratacao do dia inteiro sem carregar um trambolho.',
      emotionPositive: 'Sensacao de vida organizada, saude',
      emotionNegative: 'Preguica de levantar pra encher, desidratacao',
      ranking: 3
    },
    {
      id: 'f5', category: 'functional', feature: 'Tampa com canudo (casa/escritorio)',
      why: 'Beber sem parar o que esta fazendo. Automatico.',
      whatItDoes: 'Permite beber sem inclinar a garrafa, sem tirar os olhos do que esta fazendo.',
      dimensioned: 'Coloca do lado no escritorio e bebe o dia inteiro no automatico.',
      emotionPositive: 'Praticidade, conforto, habito saudavel sem esforco',
      emotionNegative: 'Preguica de pegar garrafa e desenroscar tampa toda hora',
      ranking: 5
    },
    {
      id: 'f6', category: 'functional', feature: 'Tampa FreeSip (rua/academia)',
      why: 'Escolher entre gole direto ou canudo. Versatilidade.',
      whatItDoes: 'Oferece duas formas de beber: gole direto (rapido) ou canudo (delicado, sem borrar batom).',
      dimensioned: 'Uma tampa que entende que voce tem dois modos: pressa e conforto.',
      emotionPositive: 'Inteligencia, adaptabilidade, controle',
      emotionNegative: 'Arrependimento de comprar algo limitado a um uso so',
      ranking: 5
    },
    {
      id: 'f7', category: 'functional', feature: '2 tampas intercambiaveis incluidas',
      why: 'Nao precisa comprar nada separado. Ja vem completa.',
      whatItDoes: 'Elimina a necessidade de comprar acessorios extras.',
      dimensioned: 'Uma garrafa, dois usos, zero acessorio extra. Pronta pra tudo.',
      emotionPositive: 'Satisfacao, economia, praticidade',
      emotionNegative: 'Frustacao de comprar e descobrir que falta peca',
      ranking: 5
    },
    {
      id: 'f8', category: 'functional', feature: 'Vedacao a prova de vazamentos',
      why: 'Jogar na bolsa sem medo. Sem estragar maquiagem, celular, documentos.',
      whatItDoes: 'Impede qualquer vazamento mesmo deitada dentro da bolsa ou mochila.',
      dimensioned: 'Joga na bolsa e esquece. Paz de espirito total.',
      emotionPositive: 'Tranquilidade, confianca, paz',
      emotionNegative: 'Ansiedade com vazamento, raiva de bolsa molhada',
      ranking: 4
    },
    {
      id: 'f9', category: 'functional', feature: 'Material que nao pega gosto',
      why: 'Alterna entre agua, cafe, suco, pre-treino sem contaminacao.',
      whatItDoes: 'Permite alternar entre diferentes bebidas sem gosto residual.',
      dimensioned: 'Pre-treino ontem, agua hoje. Zero gosto. Aco inoxidavel e outro nivel.',
      emotionPositive: 'Limpeza, versatilidade, praticidade',
      emotionNegative: 'Nojo de gosto de plastico ou de bebida anterior',
      ranking: 3
    },
    {
      id: 'f10', category: 'aesthetic', feature: '19 cores e estampas disponiveis',
      why: 'Escolher algo que e a cara dela. Expressao pessoal.',
      whatItDoes: 'Transforma um objeto utilitario em acessorio de moda e expressao pessoal.',
      dimensioned: 'Um catalogo de cores tao lindo que voce vai querer mais de uma. E outra. E outra.',
      emotionPositive: 'Vaidade, autoexpressao, pertencimento, admiracao das amigas',
      emotionNegative: 'Vergonha de usar garrafa feia/generica, sentir que esta por fora',
      ranking: 5
    },
    {
      id: 'f11', category: 'aesthetic', feature: 'Edicoes limitadas',
      why: 'Escassez gera desejo. Se nao comprar agora, acaba.',
      whatItDoes: 'Cria urgencia e exclusividade.',
      dimensioned: 'Edicao limitada miga, se nao correr acaba. E nao volta.',
      emotionPositive: 'Exclusividade, urgencia, ser especial',
      emotionNegative: 'FOMO, medo de perder, arrependimento',
      ranking: 4
    },
    {
      id: 'f12', category: 'aesthetic', feature: 'Acabamento premium',
      why: 'Parece caro. As amigas perguntam onde comprou.',
      whatItDoes: 'Eleva a percepcao de valor muito acima do preco real.',
      dimensioned: 'Parece que custa 200 reais e custa 80. Todo mundo pergunta de onde e.',
      emotionPositive: 'Orgulho, status, sofisticacao',
      emotionNegative: 'Medo de parecer barato, vergonha do que usa',
      ranking: 5
    },
    {
      id: 'f13', category: 'commercial', feature: 'Preco R$80,80 com frete gratis',
      why: 'Acessivel pra impulso, premium o suficiente pra valorizar.',
      whatItDoes: 'Remove barreiras financeiras e facilita a decisao imediata.',
      dimensioned: '80 reais com frete gratis por uma garrafa de aco que parece de grife.',
      emotionPositive: 'Sensacao de negocio bom, inteligencia de compra',
      emotionNegative: 'Culpa de gastar, medo de nao valer a pena',
      ranking: 4
    },
    {
      id: 'f14', category: 'commercial', feature: 'Disponivel no TikTok Shop',
      why: 'Viu no video, clicou, comprou. Sem sair do app.',
      whatItDoes: 'Encurta o caminho entre desejo e compra para segundos.',
      dimensioned: 'Do video pro carrinho em 3 toques. Impulso puro.',
      emotionPositive: 'Conveniencia, facilidade, gratificacao instantanea',
      emotionNegative: 'Preguica de procurar em outro site, desistir no meio',
      ranking: 3
    },
  ],
  mainBenefit: 'Beleza e estetica — a garrafa e comprada como acessorio de moda, nao como recipiente de liquido. 88% das avaliacoes mencionam beleza/cor/design.',
  decisionPyramid: {
    desire: 'DESEJO pela beleza (88% das avaliacoes) — "que linda, preciso dessa"',
    justification: 'JUSTIFICATIVA pela praticidade (64%) — "e pratica, cabe na bolsa"',
    rationalization: 'RACIONALIZACAO pela funcionalidade (30%) — "e termica, vale o preco"',
    conversion: 'CONVERSAO pela facilidade (20%) — "frete gratis, desconto, facil de comprar"',
  },
  objections: [
    { objection: 'Uma tampa veda e a outra vaza', source: '1 avaliacao', treatment: 'Mostrar fechando e virando de cabeca pra baixo nos dois modos. A grande maioria confirma vedacao.' },
    { objection: 'Canudo exige succao mais forte', source: '2 avaliacoes', treatment: 'Demonstrar usando normalmente. Explicar que e normal em garrafas termicas de aco (vacuo cria resistencia).' },
    { objection: 'Preco de R$80 pra garrafa', source: 'Objecao implicita', treatment: 'Comparar com Stanley/concorrentes. Reforcar que vem com DUAS tampas. Mostrar durabilidade e que parece mais cara.' },
  ],
  strategicInsights: [
    'A Hilee 2 em 1 NAO e vendida como garrafa termica. E vendida como acessorio de moda funcional. A comunicacao deve SEMPRE liderar com estetica.',
    'O publico coleciona. 19 cores + edicoes limitadas = engine de recompra. Cada video deve mostrar UMA cor de forma irresistivel.',
    'O tamanho 500ml domina (64% das avaliacoes), mas o 350ml tem nicho forte em bolsa pequena e uso infantil.',
    'A compatibilidade de tampas e subutilizada na comunicacao. E argumento forte de ecossistema.',
    'O diferencial real vs concorrencia interna Hilee: as 2 tampas incluidas. As outras Hilee vendem mais unidades mas sao tampa unica.',
    'Frases reais das avaliacoes sao ouro para scripts: usar aspas de clientes gera prova social massiva.',
    'Perfil da compradora tipica: Mulher, 20-35, urbana, trabalha em escritorio, se preocupa com estetica, compra por impulso emocional e justifica com razao pratica.',
  ],
}];
